-- all the codes of table from supabase database that is current defination of all table
create table public.reservations (
  id bigint generated by default as identity not null,
  guest_id bigint null,
  room_id bigint null,
  check_in date not null,
  check_out date not null,
  status text not null default 'pending'::text,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  admin_deleted_at timestamp with time zone null,
  guests_count bigint null,
  reserved_price bigint not null,
  constraint reservations_pkey primary key (id),
  constraint reservations_guest_id_fkey foreign KEY (guest_id) references guests (id) on delete CASCADE,
  constraint reservations_room_id_fkey foreign KEY (room_id) references rooms (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.guests (
  id bigint generated by default as identity not null,
  fullname text not null,
  email text not null,
  "nationalID" text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  phone text null,
  nationality text null,
  "countryFlag" text null,
  constraint guests_pkey primary key (id),
  constraint guests_email_key unique (email),
  constraint guests_nationalid_key unique ("nationalID")
) TABLESPACE pg_default;

create table public.inbox (
  id bigint generated by default as identity not null,
  sender_name text not null,
  sender_email text not null,
  message text not null,
  is_read boolean null default false,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint inbox_pkey primary key (id)
) TABLESPACE pg_default;

create table public.logs (
  id bigint generated by default as identity not null,
  action text not null,
  description text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint logs_pkey primary key (id)
) TABLESPACE pg_default;

create table public.rooms (
  id bigint generated by default as identity not null,
  name text not null,
  price numeric(10, 2) not null,
  capacity integer not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  sleeps integer not null,
  available boolean null default true,
  discount numeric(10, 2) null default 0,
  slug text not null,
  status text null default 'available'::text,
  property_id bigint null,
  bed_type text null,
  bed_count integer null default 1,
  room_type text null,
  constraint rooms_pkey primary key (id),
  constraint rooms_property_id_fkey foreign KEY (property_id) references properties (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.users (
  id uuid not null,
  full_name text null,
  avatar_url text null,
  is_anonymous boolean null default false,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint users_pkey primary key (id),
  constraint users_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.properties (
  id bigint generated by default as identity not null,
  name text not null,
  description text null,
  address text not null,
  city text not null,
  state text null,
  pincode text null,
  property_type text not null,
  thumbnail text null,
  images text[] null,
  status text null default 'available'::text,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  amenities jsonb null default '{"ac": false, "tv": false, "wifi": false, "balcony": false, "kitchen": false, "parking": false}'::jsonb,
  landmark text null,
  bhk text null,
  constraint properties_pkey primary key (id)
) TABLESPACE pg_default;